### ISSUE TITLE
What are the default Ghost account credentials?

### ISSUE THREAD

**Issue by jpsim** [TryGhost/Ghost-Vagrant#70]
Thanks for this project, it helped me get Ghost up and running on my machine where a direct installation always failed!

I'm stuck now though because it seems as though a ghost account was automatically created, but I can't find the credentials to access it anywhere in this repo or in tryghost/ghost.

I tried creating an account at `http://local.tryghost.org/ghost/setup`, but that failed (briefly displaying a URL mismatch error, I think) and now I can't get back to that setup page `http://local.tryghost.org/ghost/setup` redirects to `http://local.tryghost.org/ghost/signin` and the credentials I entered in `/setup` aren't accepted.

Any help is appreciated, thanks!

**Comment by ErisDS** [comment]
There are no default account credentials, they'll be what you entered. The url error you encountered is likely [this](http://support.ghost.org/config/#url). Quickest way to solve the issue is to delete the DB, configure Ghost and start over.

Would be good to get vagrant to automatically set the URL correctly but I'm not sure this is easy.

**Comment by jpsim** [comment]
Thanks for your response.
